# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c40f24d0537be1a568918dfa1e799bcce82369e547ea0800c4bd9cf4093368ae57511db55674cb82440273cc9529ced4575801448f894084b9f9b0a97c2959c

test:
  secret_key_base: 58bfe8416d139196b44844f2c494768b87239d97bd03ebc7002d5470ffa773782c5147fc400f7a82e83a7c3ba7263515beadcbbfc27126110b77aa68c60034ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
